/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class Calculator extends javax.swing.JFrame {
    String angka;
    double total, angka1, angka2;
    int pilih;
    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
        this.setLocationRelativeTo(null);
        angka="";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        display = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnhapus = new java.awt.Button();
        btnangkasatu = new java.awt.Button();
        btnangkaempat = new java.awt.Button();
        btnpersen = new java.awt.Button();
        btnangkadua = new java.awt.Button();
        btnangkalima = new java.awt.Button();
        btnbagi = new java.awt.Button();
        btnkali = new java.awt.Button();
        btnkurang = new java.awt.Button();
        btntambah = new java.awt.Button();
        btnangkadelapan = new java.awt.Button();
        btnangkatujuh = new java.awt.Button();
        btnsamadengan = new java.awt.Button();
        btnkosong = new java.awt.Button();
        btnkoma = new java.awt.Button();
        btnangkasembilan = new java.awt.Button();
        btnangkaenam = new java.awt.Button();
        btnangkatiga = new java.awt.Button();
        btnplusminus = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        display.setBackground(new java.awt.Color(204, 204, 204));
        display.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(display)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(display, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnhapus.setBackground(new java.awt.Color(186, 210, 255));
        btnhapus.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnhapus.setLabel("C");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnangkasatu.setBackground(new java.awt.Color(74, 144, 226));
        btnangkasatu.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnangkasatu.setLabel("1");
        btnangkasatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnangkasatuActionPerformed(evt);
            }
        });

        btnangkaempat.setBackground(new java.awt.Color(122, 178, 252));
        btnangkaempat.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnangkaempat.setLabel("4");
        btnangkaempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnangkaempatActionPerformed(evt);
            }
        });

        btnpersen.setBackground(new java.awt.Color(186, 210, 255));
        btnpersen.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnpersen.setLabel("%");
        btnpersen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpersenActionPerformed(evt);
            }
        });

        btnangkadua.setBackground(new java.awt.Color(90, 155, 240));
        btnangkadua.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnangkadua.setLabel("2");
        btnangkadua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnangkaduaActionPerformed(evt);
            }
        });

        btnangkalima.setBackground(new java.awt.Color(138, 189, 252));
        btnangkalima.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnangkalima.setLabel("5");
        btnangkalima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnangkalimaActionPerformed(evt);
            }
        });

        btnbagi.setBackground(new java.awt.Color(52, 120, 246));
        btnbagi.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnbagi.setLabel("/");
        btnbagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbagiActionPerformed(evt);
            }
        });

        btnkali.setBackground(new java.awt.Color(52, 120, 246));
        btnkali.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnkali.setLabel("*");
        btnkali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkaliActionPerformed(evt);
            }
        });

        btnkurang.setBackground(new java.awt.Color(52, 120, 246));
        btnkurang.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnkurang.setLabel("-");
        btnkurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkurangActionPerformed(evt);
            }
        });

        btntambah.setBackground(new java.awt.Color(52, 120, 246));
        btntambah.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btntambah.setLabel("+");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        btnangkadelapan.setBackground(new java.awt.Color(182, 215, 255));
        btnangkadelapan.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnangkadelapan.setLabel("8");
        btnangkadelapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnangkadelapanActionPerformed(evt);
            }
        });

        btnangkatujuh.setBackground(new java.awt.Color(170, 210, 254));
        btnangkatujuh.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnangkatujuh.setLabel("7");
        btnangkatujuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnangkatujuhActionPerformed(evt);
            }
        });

        btnsamadengan.setBackground(new java.awt.Color(33, 99, 235));
        btnsamadengan.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnsamadengan.setLabel("=");
        btnsamadengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsamadenganActionPerformed(evt);
            }
        });

        btnkosong.setBackground(new java.awt.Color(208, 232, 255));
        btnkosong.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnkosong.setLabel("0");
        btnkosong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkosongActionPerformed(evt);
            }
        });

        btnkoma.setBackground(new java.awt.Color(186, 210, 255));
        btnkoma.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnkoma.setLabel(",");
        btnkoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkomaActionPerformed(evt);
            }
        });

        btnangkasembilan.setBackground(new java.awt.Color(194, 222, 255));
        btnangkasembilan.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnangkasembilan.setLabel("9");
        btnangkasembilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnangkasembilanActionPerformed(evt);
            }
        });

        btnangkaenam.setBackground(new java.awt.Color(154, 200, 253));
        btnangkaenam.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnangkaenam.setLabel("6");
        btnangkaenam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnangkaenamActionPerformed(evt);
            }
        });

        btnangkatiga.setBackground(new java.awt.Color(106, 166, 248));
        btnangkatiga.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnangkatiga.setLabel("3");
        btnangkatiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnangkatigaActionPerformed(evt);
            }
        });

        btnplusminus.setBackground(new java.awt.Color(186, 210, 255));
        btnplusminus.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnplusminus.setLabel("+/-");
        btnplusminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplusminusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnkosong, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnkoma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnangkasatu, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(btnhapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnangkadua, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnangkatiga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnpersen, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnplusminus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnangkatujuh, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnangkadelapan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(btnangkaempat, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnangkalima, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnangkaenam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnangkasembilan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnbagi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnkali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnkurang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btntambah, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(btnsamadengan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnpersen, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(btnplusminus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnbagi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnhapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnkali, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(btnangkatiga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnangkadua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnangkasatu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnkurang, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(btnangkaenam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnangkaempat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnangkalima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btntambah, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(btnangkasembilan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnangkadelapan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnangkatujuh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnkoma, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(btnkosong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsamadengan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        display.setText("");
        angka1=0.0;
        angka2=0.0;
        total=0.0;
        angka="";// TODO add your handling code here:
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnkomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkomaActionPerformed
        angka+=".";
        display.setText(angka);// TODO add your handling code here:
    }//GEN-LAST:event_btnkomaActionPerformed

    private void btnkosongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkosongActionPerformed
        angka+="0";
        display.setText(angka);// TODO add your handling code here:
    }//GEN-LAST:event_btnkosongActionPerformed

    private void btnangkasatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnangkasatuActionPerformed
        angka+="1";
        display.setText(angka);// TODO add your handling code here:
    }//GEN-LAST:event_btnangkasatuActionPerformed

    private void btnangkaduaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnangkaduaActionPerformed
        angka+="2";
        display.setText(angka);// TODO add your handling code here:
    }//GEN-LAST:event_btnangkaduaActionPerformed

    private void btnangkatigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnangkatigaActionPerformed
        angka+="3";
        display.setText(angka);// TODO add your handling code here:
    }//GEN-LAST:event_btnangkatigaActionPerformed

    private void btnangkaempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnangkaempatActionPerformed
        angka+="4";
        display.setText(angka);// TODO add your handling code here:
    }//GEN-LAST:event_btnangkaempatActionPerformed

    private void btnangkalimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnangkalimaActionPerformed
        angka+="5";
        display.setText(angka);// TODO add your handling code here:
    }//GEN-LAST:event_btnangkalimaActionPerformed

    private void btnangkaenamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnangkaenamActionPerformed
        angka+="6";
        display.setText(angka);// TODO add your handling code here:
    }//GEN-LAST:event_btnangkaenamActionPerformed

    private void btnangkatujuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnangkatujuhActionPerformed
        angka+="7";
        display.setText(angka);// TODO add your handling code here:
    }//GEN-LAST:event_btnangkatujuhActionPerformed

    private void btnangkadelapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnangkadelapanActionPerformed
        angka+="8";
        display.setText(angka);// TODO add your handling code here:
    }//GEN-LAST:event_btnangkadelapanActionPerformed

    private void btnangkasembilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnangkasembilanActionPerformed
        angka+="9";
        display.setText(angka);// TODO add your handling code here:
    }//GEN-LAST:event_btnangkasembilanActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        angka1=Double.parseDouble(angka);
        display.setText("+");
        angka="";
        pilih=1;// TODO add your handling code here:
    }//GEN-LAST:event_btntambahActionPerformed

    private void btnkurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkurangActionPerformed
        angka1=Double.parseDouble(angka);
        display.setText("+");
        angka="";
        pilih=2;// TODO add your handling code here:
    }//GEN-LAST:event_btnkurangActionPerformed

    private void btnkaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkaliActionPerformed
        angka1=Double.parseDouble(angka);
        display.setText("+");
        angka="";
        pilih=3;// TODO add your handling code here:
    }//GEN-LAST:event_btnkaliActionPerformed

    private void btnpersenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpersenActionPerformed
        angka2=Double.parseDouble(angka);
        total=angka2/100;
        angka=Double.toString(total);
        display.setText(angka);// TODO add your handling code here:
    }//GEN-LAST:event_btnpersenActionPerformed

    private void btnbagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbagiActionPerformed
        angka1=Double.parseDouble(angka);
        display.setText("!");
        angka="";
        pilih=4;// TODO add your handling code here:
    }//GEN-LAST:event_btnbagiActionPerformed

    private void btnplusminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplusminusActionPerformed
        angka2=Double.parseDouble(angka);
        total=0-angka2;
        angka=Double.toString(total);
        display.setText(angka);// TODO add your handling code here:
    }//GEN-LAST:event_btnplusminusActionPerformed

    private void btnsamadenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsamadenganActionPerformed
        switch (pilih){
                case 1:
                angka2=Double.parseDouble(angka);
                total=angka1 + angka2 ;
                angka=Double.toString(total);
                display.setText(angka);
                break;
        
                case 2:
                angka2=Double.parseDouble(angka);
                total=angka1 - angka2 ;
                angka=Double.toString(total);
                display.setText(angka);
                break;

                case 3:
                angka2=Double.parseDouble(angka);
                total=angka1 * angka2 ;
                angka=Double.toString(total);
                display.setText(angka);
                break;

                case 4:
                angka2=Double.parseDouble(angka);
                total=angka1 / angka2 ;
                angka=Double.toString(total);
                display.setText(angka);
                break;
                default:
                break;// TODO add your handling code here:
    }//GEN-LAST:event_btnsamadenganActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnangkadelapan;
    private java.awt.Button btnangkadua;
    private java.awt.Button btnangkaempat;
    private java.awt.Button btnangkaenam;
    private java.awt.Button btnangkalima;
    private java.awt.Button btnangkasatu;
    private java.awt.Button btnangkasembilan;
    private java.awt.Button btnangkatiga;
    private java.awt.Button btnangkatujuh;
    private java.awt.Button btnbagi;
    private java.awt.Button btnhapus;
    private java.awt.Button btnkali;
    private java.awt.Button btnkoma;
    private java.awt.Button btnkosong;
    private java.awt.Button btnkurang;
    private java.awt.Button btnpersen;
    private java.awt.Button btnplusminus;
    private java.awt.Button btnsamadengan;
    private java.awt.Button btntambah;
    private javax.swing.JTextField display;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
